# Site settings
title: deh.li
description: "CP Dehli's personal website."

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - octopress-paginate

sass:
  style: compressed

include:
  - _redirects
  - keybase.txt
