# Site settings
title: deh.li
description: "CP Dehli's personal website."
url: "https://deh.li"

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-feed
  - octopress-paginate

sass:
  style: compressed

include:
  - _redirects
  - keybase.txt

# Dev settings
incremental: true
livereload: true
