# Site settings
title: Dehli
email: cp@dehli.io
description: "Christian Paul Dehli's awesome portfolio website."

# Social networks usernames
social:
  - title: linkedin
    url: http://linkedin.com/in/dehli
  - title: google-plus
    url: http://google.com/+ChristianDehli
  - title: github
    url: http://github.com/dehli
  - title: stack-overflow
    url: http://stackoverflow.com/users/2411075/dehli
  - title: bitbucket
    url: http://bitbucket.org/dehli
  - title: twitter
    url: //twitter.com/cpdehli
  - title: facebook
    url: //facebook.com/sippyy

# Build settings
markdown: kramdown
permalink: pretty
