# Site settings
title: Dehli
email: cp@dehli.io
description: "C.P. Dehli's portfolio website."

# Social networks usernames
social:
  - title: linkedin
    url: http://linkedin.com/in/dehli
  - title: stack-overflow
    url: http://stackoverflow.com/users/2411075/dehli
  - title: github
    url: http://github.com/dehli
  - title: google-plus
    url: http://google.com/+ChristianDehli
  - title: twitter
    url: //twitter.com/cpdehli

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock