# Site settings
title: Dehli
email: cp@dehli.io
description: "C.P. Dehli's portfolio website."

# Social networks
social:
  - title: linkedin
    url: //linkedin.com/in/dehli
  - title: github
    url: //github.com/dehli

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock